import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <main className="flex flex-col justify-center gap-4 items-center h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hi Next.js!</h1>
    </main>
  );
}
